from enum import Enum

class TokenMetadataEnum(Enum):
    name = "name"
    symbol = "symbol"
    tokenAddress = "tokenAddress"
    decimals = "decimals"
    score = "score"
    deployedAgo = "deployedAgo"
    logoUrl = "logoUrl"
    chain = "chain"
    twitter = "twitter"
    telegram = "telegram"
    discord = "discord"
    webUrl = "webUrl"
    buyLink = "buyLink"
    lockedLiquidity = "lockedLiquidity"
    burnedLiquidity = "burnedLiquidity"
    buyTax = "buyTax"
    sellTax = "sellTax"
    liquidityUsd = "liquidityUsd"
    liquiditySingleSided = "liquiditySingleSided"
    volume24h = "volume24h"
    circulatingSupply = "circulatingSupply"
    totalSupply = "totalSupply"
    totalSupplyPercentage = "totalSupplyPercentage"
    contractDeployer = "contractDeployer"
    lastUpdatedTimestamp = "lastUpdatedTimestamp"
    txCount = "txCount"
    holders = "holders"
