MOST_VIEWED_TOKENS_STALENESS_THRESHOLD = 60 * 3  # 3 hours
MOST_VIEWED_TOKENS_LIMIT = 10
MOST_VIEWED_TOKENS_NUM_MINUTES = 60 * 60 * 6  # 6 hours
TOP_EVENTS_STALENESS_THRESHOLD = 60 * 60 * 3  # 3 hours
TOP_EVENTS_LIMIT = 5
TOP_EVENTS_NUM_MINUTES = 60 * 60 * 6  # 6 hours
