name: Deploy to EC2

on:
  push:
    branches:
      - CICD

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: <your-aws-region>

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build and push Docker image to ECR
        run: |
          docker build -t <ecr-repository-uri>:<tag> .
          docker push <ecr-repository-uri>:<tag>

      - name: SSH into EC2 instance and deploy Docker image
        uses: appleboy/ssh-action@master
        with:
          host: <ec2-instance-ip>
          username: <ec2-instance-username>
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: <ec2-instance-ssh-port>
          script: |
            docker pull <ecr-repository-uri>:<tag>
            docker run -d --name <container-name> <ecr-repository-uri>:<tag>
